#pragma once

#include <FL/Enumerations.H>  
#include <FL/fl_draw.H>
#include <string>



//Window
const Fl_Color grey_green = fl_rgb_color(157, 201, 157);
const int WW = 600;
const int WH = 370;
const std::string WTitle = "Lab 1";

//"N: " label
const int SNY = 23;
const int SNX = WW - 40; //200 - RIGHT CORNER
const int LNY = 3;
const int LNX = WW - SNX - 2;
const std::string TN = "N: ";

//Tabs container
const int TX = 0;
const int TY = 30;
const Fl_Color dark_grey_green = fl_rgb_color(167, 191, 167);

//Task Size
const int TASK_X = TX;
const int TASK_Y = TY + 30;

//Task 1 preset
const int SIMULATE_TASK_BUTTON_X = TASK_X + 15;
const int SIMULATE_TASK_BUTTON_Y = TASK_Y + 60;
const int SIMULATE_TASK_BUTTON_SX = 200;
const int SIMULATE_TASK_BUTTON_SY = 50;
const std::string SIMULATE_TASK_BUTTON_TEXT = "SIMULATE";

const int SIMULATE_RESULT_X = SIMULATE_TASK_BUTTON_X;
const int SIMULATE_RESULT_Y = SIMULATE_TASK_BUTTON_Y - 40;
const int SIMULATE_RESULT_SX = SIMULATE_TASK_BUTTON_SX;
const int SIMULATE_RESULT_SY = SIMULATE_TASK_BUTTON_SY;

const int SIMULATE_RECTANGLE_X = SIMULATE_RESULT_X - 5;
const int SIMULATE_RECTANGLE_Y = SIMULATE_RESULT_Y - 5;
const int SIMULATE_RECTANGLE_SX = SIMULATE_TASK_BUTTON_SX + 10;
const int SIMULATE_RECTANGLE_SY = SIMULATE_TASK_BUTTON_SY + SIMULATE_RESULT_SY + 10;

const int PY = SIMULATE_RECTANGLE_Y;
const int PX = SIMULATE_RECTANGLE_X + SIMULATE_RECTANGLE_SX + 50; //200 - RIGHT CORNER
const int PSY = 40;
const int PSX = 200;
const std::string PT = "P: ";

const int SIMULATE_MULTIPLE_TASK_BUTTON_X = SIMULATE_TASK_BUTTON_X;
const int SIMULATE_MULTIPLE_TASK_BUTTON_Y = SIMULATE_TASK_BUTTON_Y + 150;
const int SIMULATE_MULTIPLE_TASK_BUTTON_SX = WW - 30;
const int SIMULATE_MULTIPLE_TASK_BUTTON_SY = 50;
const std::string SIMULATE_MULTIPLE_TASK_BUTTON_TEXT = "SIMULATE N EVENTS";

const int SIMULATE_MULTIPLE_TASK_RESULT_X = SIMULATE_MULTIPLE_TASK_BUTTON_X;
const int SIMULATE_MULTIPLE_TASK_RESULT_Y = SIMULATE_MULTIPLE_TASK_BUTTON_Y - 40;
const int SIMULATE_MULTIPLE_TASK_RESULT_SX = SIMULATE_MULTIPLE_TASK_BUTTON_SX;
const int SIMULATE_MULTIPLE_TASK_RESULT_SY = SIMULATE_MULTIPLE_TASK_BUTTON_SY;
const std::string SIMULATE_MULTIPLE_TASK_RESULT_TEXT = "Multiple run result: ";

const int SIMULATE_MULTIPLE_RECTANGLE_X = SIMULATE_MULTIPLE_TASK_RESULT_X - 5;
const int SIMULATE_MULTIPLE_RECTANGLE_Y = SIMULATE_MULTIPLE_TASK_RESULT_Y - 5;
const int SIMULATE_MULTIPLE_RECTANGLE_SX = SIMULATE_MULTIPLE_TASK_BUTTON_SX + 10;
const int SIMULATE_MULTIPLE_RECTANGLE_SY = SIMULATE_MULTIPLE_TASK_BUTTON_SY + SIMULATE_MULTIPLE_TASK_RESULT_SY + 10;

//Task 2 preset
const int PROBABILITIES_K_LIST_LABEL_X = 5;
const int PROBABILITIES_K_LIST_LABEL_Y = TASK_Y + 10;
const int PROBABILITIES_K_LIST_LABEL_SX = 20;
const int PROBABILITIES_K_LIST_LABEL_SY = 15;

const int PROBABILITIES_LIST_INPUT_X = PROBABILITIES_K_LIST_LABEL_X;
const int PROBABILITIES_LIST_INPUT_Y = PROBABILITIES_K_LIST_LABEL_Y + PROBABILITIES_K_LIST_LABEL_SY + 10;
const int PROBABILITIES_LIST_INPUT_SX = WW / 3;
const int PROBABILITIES_LIST_INPUT_SY = WH - PROBABILITIES_LIST_INPUT_Y - 50;

const int SIMULATE_K_LIST_PROBABILITIES_X = PROBABILITIES_LIST_INPUT_X;
const int SIMULATE_K_LIST_PROBABILITIES_Y = PROBABILITIES_LIST_INPUT_Y + PROBABILITIES_LIST_INPUT_SY + 5;
const int SIMULATE_K_LIST_PROBABILITIES_SX = PROBABILITIES_LIST_INPUT_SX;
const int SIMULATE_K_LIST_PROBABILITIES_SY = 40;
const std::string SIMULATE_K_LIST_PROBABILITIES_TEXT = "SIMULATE";

const int PROBABILITIES_RESULT_K_LIST_LABEL_X = PROBABILITIES_LIST_INPUT_X + PROBABILITIES_LIST_INPUT_SX + 50;
const int PROBABILITIES_RESULT_K_LIST_LABEL_Y = PROBABILITIES_K_LIST_LABEL_Y;
const int PROBABILITIES_RESULT_K_LIST_LABEL_SX = PROBABILITIES_LIST_INPUT_SX;
const int PROBABILITIES_RESULT_K_LIST_LABEL_SY = PROBABILITIES_K_LIST_LABEL_SY;

const int PROBABILITIES_LIST_OUTPUT_X = PROBABILITIES_RESULT_K_LIST_LABEL_X;
const int PROBABILITIES_LIST_OUTPUT_Y = PROBABILITIES_LIST_INPUT_Y;
const int PROBABILITIES_LIST_OUTPUT_SX = PROBABILITIES_LIST_INPUT_SX;
const int PROBABILITIES_LIST_OUTPUT_SY = PROBABILITIES_LIST_INPUT_SY;

const int SIMULATE_MULTI_LIST_PROBABILITIES_X = SIMULATE_K_LIST_PROBABILITIES_X + SIMULATE_K_LIST_PROBABILITIES_SX + 40;
const int SIMULATE_MULTI_LIST_PROBABILITIES_Y = SIMULATE_K_LIST_PROBABILITIES_Y;
const int SIMULATE_MULTI_LIST_PROBABILITIES_SX = SIMULATE_K_LIST_PROBABILITIES_SX + 20;
const int SIMULATE_MULTI_LIST_PROBABILITIES_SY = SIMULATE_K_LIST_PROBABILITIES_SY;
const std::string SIMULATE_MULTI_LIST_PROBABILITIES_TEXT = "SIMULATE N ACTIONS";